name: Flutter Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code ğŸŒ
        uses: actions/checkout@v2

      - name: Set up Flutter ğŸš€
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12' 

      - name: Install dependencies ğŸ“
        run: flutter pub get

      - name: Build Android app ğŸ“±
        run: flutter build apk

      - name: Build iOS app ğŸ“±
        run: flutter build ios
